version: "3.8"

services:
  execution:
    image: ethereum/client-go:v1.13.4
    command:
      - --networkid=28256
      - --state.scheme=path
      - --verbosity=3
      - --datadir=/execution-data
      - --http
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api=admin,engine,net,eth,web3,debug
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=admin,engine,net,eth,web3,debug
      - --ws.origins=*
      - --allow-insecure-unlock
      - --nat=extip:${IP_ADDRESS}
      - --verbosity=3
      - --authrpc.port=8551
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/el-cl-genesis-data/jwt/jwtsecret
      - --syncmode=full
      - --rpc.allow-unprotected-txs
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=9001
      - --port=50403
      - --networkid=28256
      - --bootnodes=enode://de18715ae94d2545c70f396feadf3d88da1bb0ad1a845c2b1f6d98f1075ec4c05651f0fb4388f2c256731590636a799243b7d25839848add1efffd1eecf7edf2@88.99.94.109:50303
    volumes:
      - ./execution-data:/execution-data
      - ./el-cl-genesis-data:/el-cl-genesis-data
    ports:
      - "10645:8545" 
      - "10646:8546" 
      - "10651:8551" 
      - "11101:9001" 
      - "50403:50403"
    restart: unless-stopped

  beacon:
    image: chainsafe/lodestar:latest
    command:
      - beacon 
      - --logLevel=info
      - --port=9000
      - --discoveryPort=9000
      - --dataDir=/consensus-data
      - --paramsFile=/el-cl-genesis-data/custom_config_data/config.yaml
      - --genesisStateFile=/el-cl-genesis-data/custom_config_data/genesis.ssz
      - --eth1.depositContractDeployBlock=0
      - --network.connectToDiscv5Bootnodes=true
      - --discv5=true
      - --eth1=true
      - --eth1.providerUrls=http://execution:8545
      - --execution.urls=http://execution:8551
      - --rest=true
      - --rest.address=0.0.0.0
      - --rest.namespace=*
      - --rest.port=4000
      - --nat=true
      - --enr.ip=${IP_ADDRESS}
      - --enr.tcp=9000
      - --enr.udp=9000
      - --subscribeAllSubnets=true
      - --jwt-secret=/el-cl-genesis-data/jwt/jwtsecret
      - --metrics
      - --metrics.address=0.0.0.0
      - --metrics.port=8008
      - --bootnodes=enr:-MS4QMw-J1WxLjEExb3w2DPod-15h8JVLoZtWp8-fzZjcIvqMBWZWFw90Xkfc-mNFM45WKtMXHn_jw3J-kKf8MW4qeVFh2F0dG5ldHOI__________-EZXRoMpAjvkwgQAAAOP__________gmlkgnY0gmlwhFhjXm2EcXVpY4Iq-YlzZWNwMjU2azGhAii_bzHcO9ydFheDTk140o6hvL0tnMTd89PPGnINuuORiHN5bmNuZXRzD4N0Y3CCKviDdWRwgir4
    volumes:
      - ./consensus-data:/consensus-data 
      - ./el-cl-genesis-data:/el-cl-genesis-data
    ports:
      - "11100:9000"
      - "4300:4000"
      - "7154:8008"
    depends_on:
      - execution
    restart: unless-stopped


  # lighthouse-validator:
  #   image: sigp/lighthouse:v4.5.0
  #   command:
  #    lighthouse
  #    validator_client
  #     - --debug-level=info
  #     - --testnet-dir=/el-cl-genesis-data/custom_config_data
  #     - --validators-dir=/validator-keys/node-0-keystores/keys
  #     - --secrets-dir=/validator-keys/node-0-keystores/secrets
  #     - --init-slashing-protection
  #     - --http
  #     - --unencrypted-http-transport
  #     - --http-address=0.0.0.0
  #     - --http-port=5042
  #     - --beacon-nodes=http://lighthouse-beacon:4000
  #     - --suggested-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776
  #     - --metrics
  #     - --metrics-address=0.0.0.0
  #     - --metrics-allow-origin=*
  #     - --metrics-port=5064
  #   volumes:
  #     - ./el-cl-genesis-data:/el-cl-genesis-data
  #     - ./validator-keys:/validator-keys
  #   ports:
  #     - "7042:5042"
  #     - "7064:5064"
  #   depends_on:
  #     - lighthouse-beacon
  #   restart: unless-stopped
